server:
  port: 8012
  session-timeout: 60
  tomcat.uri-encoding: UTF-8
spring:
  thymeleaf:
    cache: false
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    excluded-view-names:
    template-resolver-order:
  datasource:
    url : jdbc:mysql://192.168.16.193:3306/quartz-admin?characterEncoding=utf-8
    username : username
    password : password
    driverClassName : com.mysql.jdbc.Driver
  mail:
    host: smtp.exmail.qq.com
    username: email@email.com
    password: passowrd
    defaultEncoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          starttls:
              enable: false
              required: true

